//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herramienta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string IdSucursal {
            get {
                return ((string)(this["IdSucursal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("articulo/")]
        public string ArticuloLista {
            get {
                return ((string)(this["ArticuloLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("articulo/tipo")]
        public string TipoSeleccionar {
            get {
                return ((string)(this["TipoSeleccionar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("articulo/tipo")]
        public string TipoGuardar {
            get {
                return ((string)(this["TipoGuardar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("articulo/maximosminimos")]
        public string MaximosMinimosGuardar {
            get {
                return ((string)(this["MaximosMinimosGuardar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("articulo/preciomargen")]
        public string PrecioMargenGuardar {
            get {
                return ((string)(this["PrecioMargenGuardar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/")]
        public string RecetaLista {
            get {
                return ((string)(this["RecetaLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/detalle/")]
        public string RecetaDetalleLista {
            get {
                return ((string)(this["RecetaDetalleLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta")]
        public string RecetaInsertar {
            get {
                return ((string)(this["RecetaInsertar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/detalle")]
        public string RecetaInsertarDetalle {
            get {
                return ((string)(this["RecetaInsertarDetalle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/tipo")]
        public string RecetaTipo {
            get {
                return ((string)(this["RecetaTipo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("categoria/")]
        public string CategoriaLista {
            get {
                return ((string)(this["CategoriaLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ordenar/lista")]
        public string OrdenarLista {
            get {
                return ((string)(this["OrdenarLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("departamento")]
        public string DepartamentoLista {
            get {
                return ((string)(this["DepartamentoLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("permiso")]
        public string PermisoObtener {
            get {
                return ((string)(this["PermisoObtener"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("proveedor")]
        public string ProveedorLista {
            get {
                return ((string)(this["ProveedorLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/general")]
        public string ReporteGeneral {
            get {
                return ((string)(this["ReporteGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/general/imprimir")]
        public string ReporteImprimir {
            get {
                return ((string)(this["ReporteImprimir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formula/reporte/")]
        public string FormularioReporteRuta {
            get {
                return ((string)(this["FormularioReporteRuta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imprimir")]
        public string FormularioReporteImprimir {
            get {
                return ((string)(this["FormularioReporteImprimir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("general")]
        public string FormularioReporteGeneral {
            get {
                return ((string)(this["FormularioReporteGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sucursal")]
        public string SucursalLista {
            get {
                return ((string)(this["SucursalLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/tag")]
        public string ReporteTag {
            get {
                return ((string)(this["ReporteTag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/tag/nombre")]
        public string ReporteTagNombre {
            get {
                return ((string)(this["ReporteTagNombre"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/registros")]
        public string ReporteUltimosRegistros {
            get {
                return ((string)(this["ReporteUltimosRegistros"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("proveedor/buscar")]
        public string ProveedorBuscar {
            get {
                return ((string)(this["ProveedorBuscar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/actualizar/busqueda")]
        public string ReporteActualizarUltimoRegistro {
            get {
                return ((string)(this["ReporteActualizarUltimoRegistro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/OrdenarReceta")]
        public string Orden {
            get {
                return ((string)(this["Orden"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/OrdenarConcepto")]
        public string Concepto {
            get {
                return ((string)(this["Concepto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/ReporteCocinaExcel")]
        public string ReporteReceta {
            get {
                return ((string)(this["ReporteReceta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prueba/seleccionar")]
        public string prueba {
            get {
                return ((string)(this["prueba"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/seleccionarplatillo")]
        public string listaplatillos {
            get {
                return ((string)(this["listaplatillos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/MostrarMenu")]
        public string menu {
            get {
                return ((string)(this["menu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/Sacarcongelado")]
        public string buscarcongelados {
            get {
                return ((string)(this["buscarcongelados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/SacarCongeladoMenu")]
        public string SacarCongelado {
            get {
                return ((string)(this["SacarCongelado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/ReporteCongeladosFinal")]
        public string ReporteCongelado {
            get {
                return ((string)(this["ReporteCongelado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/BuscarArticuloCongelar")]
        public string Agrega_BuscarCongelado {
            get {
                return ((string)(this["Agrega_BuscarCongelado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/AgregarCongelado")]
        public string AgregarCongelado1 {
            get {
                return ((string)(this["AgregarCongelado1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/inavilitarCongelado")]
        public string inabilitarcongelado {
            get {
                return ((string)(this["inabilitarcongelado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/ordenartipoproducto")]
        public string ordenarproducto {
            get {
                return ((string)(this["ordenarproducto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/DetalleCocinaReceta")]
        public string DetalleRecetaCocina {
            get {
                return ((string)(this["DetalleRecetaCocina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/insertarinstrucciones")]
        public string INSERTARRUTAEIMAGEN {
            get {
                return ((string)(this["INSERTARRUTAEIMAGEN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/BuscarReceta")]
        public string Buscarrecetav1 {
            get {
                return ((string)(this["Buscarrecetav1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/eliminaringredientes")]
        public string eliminaringredientes {
            get {
                return ((string)(this["eliminaringredientes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/actualizarpresupuesto")]
        public string actualizarpresupuesto {
            get {
                return ((string)(this["actualizarpresupuesto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/actRuta_and_Instrucciones")]
        public string actualizar_ruta_e_instrucciones {
            get {
                return ((string)(this["actualizar_ruta_e_instrucciones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/SeleccionarPlatilloMenu")]
        public string TiposPlatillosDiarios {
            get {
                return ((string)(this["TiposPlatillosDiarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/InsertarMenu")]
        public string InsertarMenuDia {
            get {
                return ((string)(this["InsertarMenuDia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/SeleccionarDatosReceta")]
        public string RecetaporClave {
            get {
                return ((string)(this["RecetaporClave"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/SeleccionarTiporId")]
        public string TipoIdporNombre {
            get {
                return ((string)(this["TipoIdporNombre"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/PlatilloCongelado")]
        public string ExistenciaCongeladoMenu {
            get {
                return ((string)(this["ExistenciaCongeladoMenu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/unidad")]
        public string TipoUnidades {
            get {
                return ((string)(this["TipoUnidades"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/EditarMenuActual")]
        public string EditarMenuSemanal {
            get {
                return ((string)(this["EditarMenuSemanal"]));
            }
            set {
                this["EditarMenuSemanal"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/receta/Diario")]
        public string DiaAntes {
            get {
                return ((string)(this["DiaAntes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/receta/Diario")]
        public string DiaAntes1 {
            get {
                return ((string)(this["DiaAntes1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/receta/validarDiario")]
        public string ValidacionDiaria {
            get {
                return ((string)(this["ValidacionDiaria"]));
            }
            set {
                this["ValidacionDiaria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/receta/DiarioX2")]
        public string DiarioAntesX2 {
            get {
                return ((string)(this["DiarioAntesX2"]));
            }
            set {
                this["DiarioAntesX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/ActualizarDiarioX2_Fecha")]
        public string ActualizarDiarioFechaX2 {
            get {
                return ((string)(this["ActualizarDiarioFechaX2"]));
            }
            set {
                this["ActualizarDiarioFechaX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/ActualizarDiarioX2_Destino")]
        public string ActualizarDiarioDestinoX2 {
            get {
                return ((string)(this["ActualizarDiarioDestinoX2"]));
            }
            set {
                this["ActualizarDiarioDestinoX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/ActualizarDiarioX2")]
        public string ActualizarDiarioX2 {
            get {
                return ((string)(this["ActualizarDiarioX2"]));
            }
            set {
                this["ActualizarDiarioX2"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("articulo/actualizarcongelados")]
        public string ActualizarCongelado {
            get {
                return ((string)(this["ActualizarCongelado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/InsertarMenu")]
        public string InsertarMenuDiarios {
            get {
                return ((string)(this["InsertarMenuDiarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/SeleccionarRecId")]
        public string RecIdporClave {
            get {
                return ((string)(this["RecIdporClave"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/IngredientesPlatillos")]
        public string ListaIngredientesMenu {
            get {
                return ((string)(this["ListaIngredientesMenu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/ActualizarMenuSemanaActual")]
        public string ActualizarMenuSemanal {
            get {
                return ((string)(this["ActualizarMenuSemanal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/CargarMenuActual")]
        public string CargarSemanaActual {
            get {
                return ((string)(this["CargarSemanaActual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/RecetasDiarias")]
        public string CargarRecetasDiarias {
            get {
                return ((string)(this["CargarRecetasDiarias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/ReporteCongeladosFechado")]
        public string RepoCongeladoFechado {
            get {
                return ((string)(this["RepoCongeladoFechado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ActReceta")]
        public string RepActReceta {
            get {
                return ((string)(this["RepActReceta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/IngredienteActualizarReceta")]
        public string IngActReceta {
            get {
                return ((string)(this["IngActReceta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ReporteDiario")]
        public string ReporteDiarioX {
            get {
                return ((string)(this["ReporteDiarioX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/ActDiarioTable")]
        public string ActRecetaDiaria {
            get {
                return ((string)(this["ActRecetaDiaria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diarios/")]
        public string DiariosLista {
            get {
                return ((string)(this["DiariosLista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/EliminarPlatillo")]
        public string EliminarPlatillo {
            get {
                return ((string)(this["EliminarPlatillo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/BuscarRecetaenArticulos")]
        public string BuscarRecetaArticulos {
            get {
                return ((string)(this["BuscarRecetaArticulos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/receta/SeleccionarPlatilloMenuClave")]
        public string PlatilloporClave {
            get {
                return ((string)(this["PlatilloporClave"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ReporteDiario")]
        public string ReporteDiario {
            get {
                return ((string)(this["ReporteDiario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/ActualizarDestino")]
        public string ActualizarDestino {
            get {
                return ((string)(this["ActualizarDestino"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/RecetasparaActualizar")]
        public string ActPrecioReceta {
            get {
                return ((string)(this["ActPrecioReceta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/receta/ActualizacionRecetaMs")]
        public string ActualizacionRecetaPrecio {
            get {
                return ((string)(this["ActualizacionRecetaPrecio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/TablaNuevosPrecios")]
        public string TablaDifPrecios {
            get {
                return ((string)(this["TablaDifPrecios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.2/apiMovStock/public/")]
        public string UrlApi {
            get {
                return ((string)(this["UrlApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/TablaNuevosPreciosPlus")]
        public string TablaDifPrecioIngredientes {
            get {
                return ((string)(this["TablaDifPrecioIngredientes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ProductoActualizar")]
        public string PrecioActualizarProducto {
            get {
                return ((string)(this["PrecioActualizarProducto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/EliminarPrecioNuevoProducto")]
        public string EliminarRegistroPrecio {
            get {
                return ((string)(this["EliminarRegistroPrecio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/ActDiarioTable2")]
        public string ActRecetaDiaria2 {
            get {
                return ((string)(this["ActRecetaDiaria2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/AgregarDiarioManana")]
        public string InsertarDiariodeMañana {
            get {
                return ((string)(this["InsertarDiariodeMañana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/ActualizarDiarioManana")]
        public string ActualizarDiariodeMañana {
            get {
                return ((string)(this["ActualizarDiariodeMañana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reporte/MostrarEstadoManana")]
        public string MostrarEstadoMañana {
            get {
                return ((string)(this["MostrarEstadoMañana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ReportePlatillosdeHoy")]
        public string ReporteHoy {
            get {
                return ((string)(this["ReporteHoy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ReporteCocinaPlatillo")]
        public string ReporteCocinaPlatillo {
            get {
                return ((string)(this["ReporteCocinaPlatillo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receta/BuscarRecetaMenu")]
        public string RecetaMenuSemanal {
            get {
                return ((string)(this["RecetaMenuSemanal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/reporte/ReporteDiarioNewRegistro")]
        public string DiarioNuevoRegistro {
            get {
                return ((string)(this["DiarioNuevoRegistro"]));
            }
        }
    }
}
